version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: |
            dotnet restore
            dotnet build -c Release -o /app
    
      - run:
          working_directory: ./ValueTests
          name: "test-svc"
          command: |
            dotnet test -c Release -o /app

#     - run:
#         name: Archive
#          command: stages/04_archive.sh

      - run:
          working_directory: /app
          name: Running App
#          command: |
#            dotnet /app/ValueApi.dll
#            docker run -dp "5000:5000" "docker.io/edwardsdl/sample-netcore:latest"
            
#container_port=$(jq -r .deploy.containerPort pipeline.json)
#registry=$(jq -r .archive.registry pipeline.json)
#repository=$(jq -r .archive.repository pipeline.json)
#image="${registry}/${repository}:latest"

#docker run -dp "${container_port}:${container_port}" "${image}"
