version: 2.1
jobs:
  build:
    docker:
    - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
    - setup_remote_docker:
        docker_layer_caching: true
    - checkout
    - run:
        name: Archive
        command: |
          docker login -u "${DOCKER_USERNAME}" -p "{$DOCKER_PASSWORD}" "${registry}"
          docker build -t "${image}"  .
workflows:
  workflow:
    jobs:
    - build
