version: 2.1
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:6.0
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:
          name: Build
          command: |
            dotnet restore
            dotnet build -c Release
    
      - run:
          working_directory: ./ValueTests
          name: "test-svc"
          command: |
            dotnet test

      - run:
          name: Archive
          command: stages/04_archive.sh
